;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "update-maven-dependencies-skill")
(def path ".")
(def version "0.2.24")
(def tag "0.2.24")
(def generated-at "2020-07-29T19:15:29Z")
