;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "update-maven-dependencies-skill")
(def path ".")
(def version "0.2.13")
(def tag "v0.2.13")
(def generated-at "2020-05-02T07:50:19Z")
