;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "update-maven-dependencies-skill")
(def path ".")
(def version "0.2.22")
(def tag "0.2.22")
(def generated-at "2020-05-25T03:40:21Z")
